### ISSUE TITLE
Project doensn't build

### ISSUE THREAD

**Issue by YoniTlz** [Giuliopime/temporary-voice-channels-discord-bot#1]
Out of the box i get these errors when building the project:

`e: /Users/yonitlz/Documents/Workspace/temporary-voice-channels-discord-bot/src/main/kotlin/space/astrobot/discord/events/GuildVoiceUpdateEvent.kt: (5, 37): Unresolved reference: VoiceChannel
e: /Users/yonitlz/Documents/Workspace/temporary-voice-channels-discord-bot/src/main/kotlin/space/astrobot/discord/events/GuildVoiceUpdateEvent.kt: (36, 46): Unresolved reference: await
e: /Users/yonitlz/Documents/Workspace/temporary-voice-channels-discord-bot/src/main/kotlin/space/astrobot/discord/events/GuildVoiceUpdateEvent.kt: (53, 35): Unresolved reference: VoiceChannel
e: /Users/yonitlz/Documents/Workspace/temporary-voice-channels-discord-bot/src/main/kotlin/space/astrobot/discord/events/GuildVoiceUpdateEvent.kt: (54, 30): Unresolved reference: it
e: /Users/yonitlz/Documents/Workspace/temporary-voice-channels-discord-bot/src/main/kotlin/space/astrobot/discord/events/GuildVoiceUpdateEvent.kt: (58, 43): Unresolved reference: await
e: /Users/yonitlz/Documents/Workspace/temporary-voice-channels-discord-bot/src/main/kotlin/space/astrobot/discord/events/GuildVoiceUpdateEvent.kt: (59, 61): Unresolved reference: await
e: /Users/yonitlz/Documents/Workspace/temporary-voice-channels-discord-bot/src/main/kotlin/space/astrobot/discord/events/GuildVoiceUpdateEvent.kt: (77, 46): Unresolved reference: await
e: /Users/yonitlz/Documents/Workspace/temporary-voice-channels-discord-bot/src/main/kotlin/space/astrobot/discord/events/GuildVoiceUpdateEvent.kt: (80, 54): Unresolved reference: await
`

**Comment by Giuliopime** [comment]
Did you install the dependencies via Gradle?

**Comment by YoniTlz** [comment]
Yes, when i run the gradle build, that's when i get these errors.
<img width="404" alt="Capture d’écran 2023-02-03 à 11 45 26" src="https://user-images.githubusercontent.com/22733661/216581846-7d18ac52-0839-4596-bf31-d764655ea7a6.png">

**Comment by YoniTlz** [comment]
I think it originated from the fact tht one of the dependencies isn't available. So i checked the repo and used a more recet version of it.

I restarted from scratch, here is what i get:

astro-devlog:test: Could not find com.github.minndevelopment:jda-ktx:081a177.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Giuliopime** [comment]
![image](https://user-images.githubusercontent.com/60524738/216590489-9176760b-64db-4abc-b7d8-eea643722206.png)
Use that button to load the gradle project, not the run button

**Comment by YoniTlz** [comment]
It's the same, it doens't find the jda-ktx dependency :(

**Comment by Giuliopime** [comment]
Bumped the dependencies 👍🏼
