### ISSUE TITLE
Docker build not working

### ISSUE THREAD

**Issue by YoniTlz** [Giuliopime/temporary-voice-channels-discord-bot#2]
Hi, 

The Docker build isn't working anymore. Could you help finding a solution?
Here are the logs:

> ERROR: failed to solve: process "/bin/sh -c ./gradlew shadowJar" did not complete successfully: exit code: 1
> Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c ./gradlew shadowJar" did not complete successfully: exit code: 1

**Comment by Giuliopime** [comment]
I need more info on the error this is not enough

**Comment by YoniTlz** [comment]
Hi, i got it, somehow it is not able to get jda-ktx:

> #0 156.5 * What went wrong:
> #0 156.5 Could not determine the dependencies of task ':shadowJar'.
> #0 156.5 > Could not resolve all dependencies for configuration ':runtimeClasspath'.
> #0 156.5    > Could not resolve com.github.minndevelopment:jda-ktx:17eb77.
> #0 156.5      Required by:
> #0 156.5          project :
> #0 156.5       > Could not resolve com.github.minndevelopment:jda-ktx:17eb77.
> #0 156.5          > Could not get resource 'https://jitpack.io/com/github/minndevelopment/jda-ktx/17eb77/jda-ktx-17eb77.pom'.
> #0 156.5             > Could not GET 'https://jitpack.io/com/github/minndevelopment/jda-ktx/17eb77/jda-ktx-17eb77.pom'.
> #0 156.5                > Read timed out

**Comment by YoniTlz** [comment]
I tried changing the dependency to:
`    implementation("com.github.MinnDevelopment:jda-ktx:0.10.0-beta.1")
`

Seems to work better

**Comment by Giuliopime** [comment]
Ah yes outdated jitpack dependency
